section: screens
  pi-videowall-1:
  pi-videowall-2:
  pi-videowall-3:
  pi-videowall-4:
  pi-videowall-5:
  pi-videowall-6:
  pi-videowall-7:
  pi-videowall-8:
  pi-videowall-9:
  pi-videowall-10:
end

section: links
  pi-videowall-1:
    right = pi-videowall-3
    down  = pi-videowall-2

  pi-videowall-3:
    left  = pi-videowall-1
    right = pi-videowall-5
    down  = pi-videowall-4

  pi-videowall-5:
    left  = pi-videowall-3
    right = pi-videowall-7
    down  = pi-videowall-6

  pi-videowall-7:
    left  = pi-videowall-5
    right = pi-videowall-9
    down  = pi-videowall-8

  pi-videowall-9:
    left  = pi-videowall-7
    down  = pi-videowall-10

  pi-videowall-2:
    right = pi-videowall-4
    up    = pi-videowall-1

  pi-videowall-4:
    left  = pi-videowall-2
    right = pi-videowall-6
    up    = pi-videowall-3

  pi-videowall-6:
    left  = pi-videowall-4
    right = pi-videowall-8
    up    = pi-videowall-5

  pi-videowall-8:
    left  = pi-videowall-6
    right = pi-videowall-10
    up    = pi-videowall-7

  pi-videowall-10:
    left  = pi-videowall-8
    up    = pi-videowall-9
end

section: options
  relativeMouseMoves = true
  clipboardSharing = true
end

